# Generated by Django 3.2.12 on 2022-02-18 20:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0043_agent_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, size=None),
        ),
    ]
