# Generated by Django 3.2.12 on 2022-02-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20211104_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_list_groups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_groups',
            field=models.BooleanField(default=False),
        ),
    ]
