# Generated by Django 3.2.12 on 2022-02-23 15:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20220217_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_view_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
