# Generated by Django 3.2.12 on 2022-02-17 16:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='agents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
