# Generated by Django 3.2.12 on 2022-02-17 16:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20220217_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='agents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
