# Generated by Django 3.2.12 on 2022-02-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_groups_agents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='agents',
        ),
    ]
