# Generated by Django 3.2.12 on 2022-02-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winupdate', '0011_auto_20210917_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinUpdateManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kb', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('guid', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
