# Generated by Django 3.2.12 on 2022-02-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winupdate', '0012_winupdatemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='winupdate',
            name='allow_action_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='winupdatemanager',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
